### PR TITLE
Port to linter-plus

### PR DESCRIPTION
**Pull request by josa42**

### CODE REVIEW

**Comment by steelbrain** [comment]
Note: You can drop that line where you import linter.coffee from the linter package.
Also note that the current package is named linter-plus, not linter. It's gonna be renamed to that soon though.

**Comment by josa42** [comment]
@steelbrain The package is actually called linter. Just the repo is linter-plus. Or am I missing something? See: AtomLinter/linter-plus [package.json](https://github.com/AtomLinter/linter-plus/blob/master/package.json).

**Comment by steelbrain** [comment]
At the moment: Negative
Soon: Yep

**Comment by steelbrain** [comment]
-- Ignore my comment above --

**Pull request merged**
